DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  email VARCHAR(128) NOT NULL UNIQUE,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

DROP TABLE IF EXISTS resume;

CREATE TABLE resume (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  target_role VARCHAR(128),
  content CLOB NOT NULL,
  file_type VARCHAR(32) NOT NULL,
  file_url VARCHAR(512),
  version INT NOT NULL DEFAULT 1,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

DROP TABLE IF EXISTS job_post;

CREATE TABLE job_post (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  company_name VARCHAR(128) NOT NULL,
  position_name VARCHAR(128) NOT NULL,
  industry VARCHAR(96) NOT NULL DEFAULT '计算机/互联网',
  city VARCHAR(96),
  salary_range VARCHAR(96),
  job_direction VARCHAR(96),
  jd_content CLOB NOT NULL,
  source VARCHAR(128),
  status VARCHAR(32) NOT NULL DEFAULT 'preparing',
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

DROP TABLE IF EXISTS battle_card;

CREATE TABLE battle_card (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  resume_id BIGINT NOT NULL,
  job_post_id BIGINT NOT NULL,
  match_score INT NOT NULL DEFAULT 0,
  core_requirements CLOB,
  skill_breakdown CLOB,
  matched_points CLOB,
  weak_points CLOB,
  resume_suggestions CLOB,
  interview_focus CLOB,
  three_day_plan CLOB,
  seven_day_plan CLOB,
  risk_tips CLOB,
  raw_ai_result CLOB,
  request_hash VARCHAR(128),
  prompt_version VARCHAR(64),
  created_at TIMESTAMP
);

DROP TABLE IF EXISTS ai_call_log;

CREATE TABLE ai_call_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  scene VARCHAR(64) NOT NULL,
  request_hash VARCHAR(128),
  prompt_tokens INT,
  completion_tokens INT,
  model_name VARCHAR(128),
  cost DECIMAL(12,6),
  created_at TIMESTAMP
);
